// Create Action Types

export const API_STATUS_SUCCESS = "API_STATUS_SUCCESS"
export const API_STATUS_FAILURE = "API_STATUS_FAILURE"

export const FAMOUS_PEOPLE_QUOTES_SUCCESS = "FAMOUS_PEOPLE_QUOTES_SUCCESS"
export const FAMOUS_PEOPLE_QUOTES_FAILURE = "FAMOUS_PEOPLE_QUOTES_FAILURE"
